development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 10
  port: 3306
  username: root
  password: Spn16058!
  host: localhost
  database: messageapp_dev
test:
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: false
  database: messageapp_test
  pool: 5
  username: root
  password: Spn16058!
  host: localhost
  port: 3306
